const frases = [
  "Acredite em você e no seu potencial.",
  "Cada dia é uma nova oportunidade para recomeçar.",
  "Você é capaz de superar qualquer desafio.",
  "Pequenos passos também levam a grandes conquistas.",
  "Não desista, seu esforço valerá a pena.",
  "A persistência transforma sonhos em realidade.",
  "Confie no processo e continue avançando.",
  "Você é mais forte do que imagina.",
  "O sucesso começa quando você decide não desistir.",
  "Faça hoje algo pelo qual seu futuro agradecerá.",
  "Erros são oportunidades para aprender e crescer.",
  "Nunca é tarde para começar de novo.",
  "Acredite que coisas boas estão por vir.",
  "Seu esforço de hoje constrói o seu amanhã.",
  "Tenha coragem para seguir seus sonhos.",
  "Você consegue, mesmo quando parece difícil.",
  "Não compare sua jornada com a de ninguém.",
  "Cada conquista começa com uma decisão.",
  "Mantenha o foco e confie em si mesmo.",
  "Desafios são degraus para o crescimento.",
  "Sua determinação pode mudar sua história.",
  "Continue, mesmo que seja devagar.",
  "O impossível pode se tornar possível com dedicação.",
  "Você tem dentro de si tudo o que precisa para começar.",
  "Transforme obstáculos em oportunidades.",
  "A disciplina leva você onde a motivação não consegue.",
  "Sonhe grande e trabalhe para realizar.",
  "Seu potencial é maior do que seus medos.",
  "Não tenha medo de tentar novamente.",
  "A vitória pertence a quem não desiste.",
  "Um dia difícil não significa uma vida difícil.",
  "Você está evoluindo a cada experiência.",
  "Tenha paciência com seu próprio processo.",
  "O progresso, por menor que seja, ainda é progresso.",
  "Acredite no seu caminho.",
  "Você pode ir muito mais longe do que imagina.",
  "Nunca subestime a força de uma mente determinada.",
  "Comece onde está e use o que você tem.",
  "Seu futuro depende das escolhas que você faz hoje.",
  "Não espere o momento perfeito, comece agora.",
  "Você nasceu para conquistar grandes coisas.",
  "Mantenha a esperança mesmo nos dias difíceis.",
  "A força vem quando você decide continuar.",
  "Tudo começa com um primeiro passo.",
  "Faça o seu melhor e deixe o resto acontecer.",
  "Você não precisa ser perfeito para ser incrível.",
  "Acredite em suas possibilidades.",
  "Cada dificuldade traz uma nova lição.",
  "O esforço constante gera resultados extraordinários.",
  "Seja paciente, grandes coisas levam tempo.",
  "Seu sonho merece uma chance.",
  "Não permita que o medo decida por você.",
  "Você é capaz de escrever uma nova história.",
  "Levante a cabeça e siga em frente.",
  "A mudança começa quando você decide mudar.",
  "Seu limite muitas vezes está apenas na sua mente.",
  "Continue acreditando, mesmo quando ninguém acreditar.",
  "Você já superou dias difíceis antes e pode superar novamente.",
  "A jornada pode ser difícil, mas a recompensa vale a pena.",
  "Não pare até se orgulhar de si mesmo.",
  "Tenha fé na sua capacidade de vencer.",
  "Cada manhã traz uma nova oportunidade.",
  "Você merece alcançar seus objetivos.",
  "Transforme seus sonhos em metas e suas metas em ações.",
  "A coragem nasce quando enfrentamos nossos medos.",
  "Não desista por causa de um dia ruim.",
  "Você está mais perto do que pensa.",
  "A persistência é a chave para grandes realizações.",
  "Faça acontecer em vez de apenas esperar.",
  "Seu esforço nunca é em vão.",
  "Acredite: você consegue.",
  "Não deixe uma dificuldade definir quem você é.",
  "O sucesso é construído com pequenas atitudes diárias.",
  "Você tem capacidade para vencer essa batalha.",
  "Seja sua própria motivação.",
  "O amanhã pode ser melhor se você começar hoje.",
  "Continue caminhando, mesmo sem enxergar todo o caminho.",
  "A determinação transforma sonhos em conquistas.",
  "Você é responsável por criar novas oportunidades.",
  "Não tenha medo de crescer e mudar.",
  "Cada tentativa aproxima você do seu objetivo.",
  "Sua dedicação fará a diferença.",
  "Você pode recomeçar quantas vezes forem necessárias.",
  "O fracasso não é o fim, é parte do aprendizado.",
  "Acredite no seu potencial todos os dias.",
  "Não desista de algo que pode mudar sua vida.",
  "Você consegue superar mais do que imagina.",
  "Mantenha seus olhos no objetivo e seu coração no caminho.",
  "O sucesso começa com acreditar que é possível.",
  "Tenha coragem para fazer diferente.",
  "Você está construindo algo incrível.",
  "A força de vontade pode abrir novos caminhos.",
  "Não espere por oportunidades, crie-as.",
  "Seu melhor ainda está por vir.",
  "Continue tentando, continue aprendendo, continue crescendo.",
  "Acredite em si mesmo, principalmente quando estiver difícil.",
  "Cada novo dia é uma página em branco.",
  "Você tem o poder de transformar sua realidade.",
  "Não pare agora, você já chegou longe demais.",
  "Grandes conquistas começam com grandes atitudes.",
  "Nunca deixe de acreditar nos seus sonhos."
];
const frase = document.querySelector('.frase')
const btnFrase = document.querySelector('.btnFrase')

function mostrarFrase(){
    frase.textContent 
    let indice = Math.floor(Math.random() * frases.length)
    frase.textContent = frases[indice];
}
btnFrase.addEventListener('click', function(){
    mostrarFrase()
})